name: CI/CD pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookcrud-cicd-aws:test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/*.jar
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: staging
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test docker image
        run: |
          docker run --name bookcrud-cicd-aws --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/bookcrud-cicd-aws:test
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
            printf '.'
            sleep 5
          done
          echo "Application is up!"
          docker stop bookcrud-cicd-aws
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookcrud-cicd-aws:latest